# Generated by Django 5.2.4 on 2025-07-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_questions_delete_classtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Question_text',
            new_name='question_text',
        ),
    ]
